/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package m3uf6;


import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Raul
 */
public class TheNewGameOfTheYear extends javax.swing.JFrame {
        
    boolean comprueba;
    String info[][] = new String [4][4];
    int contador=0;

    /**
     * Creates new form TheNewGameOfTheYear
     */
    
    public TheNewGameOfTheYear() {
        
        initComponents();
        informacionTabla();
        tabla.setEnabled(false);
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sortir = new javax.swing.JButton();
        reinicia = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        recordPuntos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"?", "?", "?", "?"},
                {"?", "?", "?", "?"},
                {"?", "?", "?", "?"},
                {"?", "?", "?", "?"}
            },
            new String [] {
                "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setFocusTraversalPolicyProvider(true);
        tabla.setRowHeight(60);
        tabla.setRowSelectionAllowed(false);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jLabel1.setText("Rècord:");

        jLabel2.setText("Punts: ");

        sortir.setText("Sortir");
        sortir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sortirMouseClicked(evt);
            }
        });

        reinicia.setText("COMIENZA");
        reinicia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciaActionPerformed(evt);
            }
        });

        recordPuntos.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sortir, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reinicia, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(188, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recordPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(197, 197, 197))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(recordPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reinicia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sortir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
       int row = rowClicked();
       int colum = columClicked();
       
      if(tabla.isEnabled()){
          
      
       if(tabla.getValueAt(row, colum)=="?"){
           tabla.setValueAt(info[row][colum],row, colum);
       
            if("W".equals(info[row][colum])){               
                contador = contador*2;
            }else if ("X".equals(info[row][colum])){
                JOptionPane.showConfirmDialog(null,"Has hecho: "+contador+ "Puntos",
                "The new Game of the year",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.PLAIN_MESSAGE);
                tabla.setEnabled(false);
                
            }else{
            contador++;
            }
               
          if(Integer.valueOf(recordPuntos.getText())<contador){
             recordPuntos.setText(String.valueOf(contador));
          
          }
         
       }
        jLabel3.setText(String.valueOf(contador));
        
      }
        System.out.println(contador);
    }//GEN-LAST:event_tablaMouseClicked

    private void sortirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sortirMouseClicked
        String puntuaje=recordPuntos.getText();
        JOptionPane.showMessageDialog(this, "Has hecho: "+puntuaje+" Puntos");
        dispose();
    }//GEN-LAST:event_sortirMouseClicked

    private void reiniciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciaActionPerformed
        if (comprueba){
            reinicia.setText("REINICIO");
            vaciaArray();
            informacionTabla();      
            tabla.setEnabled(true);
        } else{
            reinicia.setText("COMIENZA");
            interrogantes();
            contador=0;
            jLabel3.setText("0");
            tabla.setEnabled(false);
        }
        //canvio el estat del boolean
        comprueba =!comprueba;
    }//GEN-LAST:event_reiniciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TheNewGameOfTheYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TheNewGameOfTheYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TheNewGameOfTheYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TheNewGameOfTheYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        int matriu[][];
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TheNewGameOfTheYear().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel recordPuntos;
    private javax.swing.JButton reinicia;
    private javax.swing.JButton sortir;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

    private int rowClicked() {
       return tabla.getSelectedRow();
    }

    private int columClicked() {
       return tabla.getSelectedColumn();
    }

    private void informacionTabla() {
           int matriz[][] = new int[4][4];
     //Omplir O          
     for (int x=0; x < matriz.length; x++) {
            for (int y=0; y < matriz[x].length; y++) {              
                    int O=79;
                    matriz[x][y] = O;                    
              }                 
}          
    //Omplir W                                      
    int contadorP = 0;
                  
                while(contadorP!=3){
                     Random r = new Random();
                  int posX = r.nextInt(4);
                  int posY = r.nextInt(4);
                   matriz[posX][posY] = 87;
                   contadorP++;                                            
                }
    //Omplir X            
    int contadorX = 0;
    
                while(contadorX!=2){
                     Random r = new Random();
                  int posX = r.nextInt(4);
                  int posY = r.nextInt(4);
                  
                  if( matriz[posX][posY] == 79){
                         matriz[posX][posY] = 88;
                        contadorX++;
              
                  }else{
                      posX = r.nextInt(4);
                      posY = r.nextInt(4);
                  }
               
                }
            
            //PASSAR MATRIU INT A ARRAY DE CHAR
      
                String dades[] = new String[4];
            int temp = 0;
            for (int x=0; x < matriz.length; x++) {
               System.out.println();
            for (int y=0; y < matriz[x].length; y++) {
                      
                    temp=matriz[x][y];
                    //passar int a char
                    char cadena = (char)temp;
                    //passar char a string
                       String cadenaString = Character.toString(cadena);
                       dades[x]=cadenaString;
                    //Lo passamos a una matriz de Strings el String   
                       info[x][y]=cadenaString;
                   
            }
            
            }
     
    }
    private void vaciaArray() {
        for(int j=0; j<4; j++){
            for(int a=0; a<4; a++){
                info[j][a]=null;
            }
        }
    }

    private void interrogantes() {
        for(int j=0; j<4; j++){
            for(int i=0; i<4; i++){
               tabla.setValueAt("?", j, i);
            }
        }
    }

  
}
