/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jocdames;

import javax.swing.JOptionPane;

/**
 *
 * @author Raul
 */
public class tablero extends javax.swing.JFrame {

    /**
     * Creates new form tablero
     */
    public tablero() {
        initComponents();
       
    }
     private static String strings = "";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salida = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablero = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        salida.setText("Sortir");
        salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salidaActionPerformed(evt);
            }
        });

        tablero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"X", null, "X", null, "X", null, "X", null},
                {null, "X", null, "X", null, "X", null, "X"},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {"O", null, "O", null, "O", null, "O", null},
                {null, "O", null, "O", null, "O", null, "O"}
            },
            new String [] {
                "Colum", "Colum", "Colum", "Colum", "Colum", "Colum", "Colum", "Colum"
            }
        ));
        tablero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablero);

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(58, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(salida)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(salida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salidaActionPerformed
        Game juego = new Game();
        juego.setVisible(true);
        //cierra anterior ventana dispose
        dispose();
    }//GEN-LAST:event_salidaActionPerformed

    private void tableroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableroMouseClicked
       int columna = obtenirColumnaClicada();
       int fila = obtenirFilaClicada();
       
       
        
        if(noHiHaOrigen()){
            if(jugaO && esO(fila, columna)){
                actualitzaNouOrigen(fila,columna);

            } else if (jugaX && esX(fila, columna)){
                actualitzaNouOrigen(fila, columna); 
            } else {
                mostrarError();
            }
        } else {
            if(movimentValid(fila, columna)){              
                if(esBuit(fila, columna) || ocupatContrari(fila, columna)){
                    mou(fila, columna);
                } else if (ocupatPropi(fila, columna)){
                    actualitzaNouOrigen(fila, columna);
                }
            } else {
                mostraErrorMoviment();
            }
    }
    
    }//GEN-LAST:event_tableroMouseClicked
        private boolean jugaX = false;
        private boolean jugaO = true;
        private int filaOrigen = -1;
        private int columnaOrigen = -1;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tablero().setVisible(true);
            }
        });
//        
//        Session sessionOne = HibernateUtil.getSessionFactory().openSession();
//        sessionOne.beginTransaction();
        
    }
    

    
    public void mostraError(){
        JOptionPane.showMessageDialog(null, "Error al sel·leccionar", "ERROR DAMES", JOptionPane.ERROR_MESSAGE);    
    }
    
 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton salida;
    private javax.swing.JTable tablero;
    // End of variables declaration//GEN-END:variables

    private int obtenirColumnaClicada() {
         return tablero.getSelectedColumn();
    }

    private int obtenirFilaClicada() {
        return tablero.getSelectedRow();
    }

    private boolean noHiHaOrigen() {
        return (this.filaOrigen == -1);
    }


     public boolean esO(int fila, int columna) {
       return ((tablero.getValueAt(fila,columna)!=null)&&(tablero.getValueAt(fila,columna).equals("O")));
    }
    
    public boolean esX(int fila, int columna) {
        return ((tablero.getValueAt(fila,columna)!=null)&&(tablero.getValueAt(fila,columna).equals("X")));
    }
    


    private void actualitzaNouOrigen(int fila, int columna) {
        this.filaOrigen = fila;
        this.columnaOrigen = columna;
    }


    private void mostrarError() {
          //falta colocar el label en el modo grafico
        jLabel1.setText("Clica una fixa teva");
        
    }

    private boolean movimentValid(int fila, int columna) {
        
        if (jugaX && (fila == filaOrigen + 1) && (columna == columnaOrigen - 1 || columna == columnaOrigen + 1)) {
                return true;
            } else if (jugaO && (fila == filaOrigen - 1) && (columna == columnaOrigen - 1 || columna == columnaOrigen + 1)) {
                return true;
            } else {
                return false;
    }
    
    
     
    }

    private boolean ocupatContrari(int fila, int columna) {   
        return ((jugaO&&esX(fila,columna))||jugaX&&esO(fila,columna));
    }

    private void mou(int fila, int columna) {
       tablero.getModel().setValueAt(tablero.getModel().getValueAt(filaOrigen, columnaOrigen), fila, columna);
       tablero.getModel().setValueAt(null, filaOrigen, columnaOrigen);
       filaOrigen=-1;
       columnaOrigen=-1;
       jugaX=jugaO;
       jugaO=!jugaX;
       guardarMoviments();
       
      
    }

    private boolean esBuit(int fila, int columna) {
        return ((tablero.getValueAt(fila,columna)==null)||tablero.getModel().getValueAt(fila, columna).equals(""));
    }

    private boolean ocupatPropi(int fila, int columna) {
      return ((jugaO&&esO(fila,columna)||jugaX&&esX(fila,columna)));     
    }

    private void mostraErrorMoviment() {
      jLabel1.setText("Error moviment");
    }

    private void guardarMoviments() {
      
        
    }
}
